### PR TITLE
use minetest.override_item and disable the abm

### PR DESCRIPTION
**Pull request by HybridDog**

### CODE REVIEW

**Comment by sofar** [comment]
Why not just delete the lines with the ABM? If it's unused, nuke it.

**Comment by HybridDog** [comment]
l'm not sure why they're there, maybe @VanessaE added them on purpose, e.g. to fix some light bug

**Comment by VanessaE** [comment]
That's exactly correct - if a node already in the world is "normal" drawtype, its param1 is, for whatever reason, set to 0.  I don't know why it happens, but with other nodes having it set that way of course causes the node to turn black.  This ABM fixes it - you can't add this mod to an existing world without keeping the ABM.

**Comment by sofar** [comment]
I think I understand.

You override the item, but you didn't recalculate the map. The map light will be black until you re-place the node. Overriding an item with a different paramtype will not cause the map to update.

**Comment by VanessaE** [comment]
Right, and as far as I know, there's no way to "recalculate" it except with an ABM.  Now, that said, we have LBMs now, which look like they'd work far better for this.

**Comment by sofar** [comment]
LBM's are not necessarily easy to work with. Check out the (open) xpanes PR for doing it all at once with a single LBM.

**Comment by HybridDog** [comment]
If it's night param1 is also 0, isn't it?

**Comment by VanessaE** [comment]
Not sure about what it does at night, but on looking at that xpanes PR, honestly it doesn't look all that complicated, no moreso than using an ABM anyways.

**Comment by VanessaE** [comment]
I'm....inclined not to worry about that extremely rare possible corner-case :smile:

**Comment by sofar** [comment]
Merged. I did have to fix the LBM, which had two issues:

1) typo in LBM name (road_works)
2) didn't actually work. I force it to re-place all trunk nodes and that works.

I still get an occasional dark trunk, but only rarely. Don't care enough.

**Comment by sofar** [comment]
10a403d35168c0fb623c7dd543083342f1ee9506
883e2b8c3005d95fec65bbc684b3f65f27e9a634

**Pull request closed without merging**
